### ISSUE TITLE
saveFieldLayoutConditionals sometimes is passed invalid JSON

### ISSUE THREAD

**Issue by billythekid** [mmikkel/Reasons-Craft3#2] opened 2020-06-08 11:31 UTC
I've tried tracking this down a little in the code but have been unable to work out just where the issue starts here.

Under certain conditions the `$conditionals` JSON passed to the `saveFieldLayoutConditionals()` method in the ReasonsService doesn't contain valid JSON and the whole thing falls apart leaving the dashboard inaccessible etc. It's like the closing brackets of the array of conditionals are missing when I dump out the failing code.

My field layout is as follows.

competitionType - radio button field with 3 values - roundRobin, elimination, winnerStaysOn
blindDrawForEachRound - lightswitch field
blindDrawRounds - matrix
roundRobinRounds - number field

If a user selects competitionType:elimination then the blindDrawForEachRound should be visible, if they turn that on, the blindDrawRounds should be visible.

If a user selects competitionType:roundRobin the roundRobinRounds should be visible.

The issue appears to present if I set up the second conditional on the competitionType toggle field. Somehow the JSON doesn't get wrapped up properly and I've struggled (although I've not looked at it in-depth) to easily find where that's hapening.

Let me know if you want a DB/project config or anything.

Cheers

**Comment by mmikkel** [comment] 2020-06-08 12:24
Thanks for reporting that @billythekid – I'm able to reproduce; will get out a fix ASAP.

**Comment by mmikkel** [comment] 2020-06-08 13:11
This turned out to be a really stupid bug on my part – the conditionals' database column had the wrong type (VARCHAR instead of TEXT), so longer/more complex conditionals could get cut off (and hence, made invalid).

Resolved in [Reasons v. 2.1.1](https://github.com/mmikkel/Reasons-Craft3/releases/tag/2.1.1), but obviously any conditionals currently truncated in the database needs to be manually recreated in the CP. Sorry about that, and thanks again for reporting the issue.

**Closed by mmikkel** 2020-06-08 13:11 UTC
Labels: bug

**Comment by billythekid** [comment] 2020-06-08 13:27
Ahhhh, nice one!

I was thinking there was some manual loop somewhere building this up that wasn't closing up properly but just couldn't see it in the code, everything looked fine (because it *was* fine!)

I've actually had a similar bug myself in one of my Laravel projects so completely get it!

No worries about the conditionals needing to be recreated, I was able to purge them out by returning an empty array in the "prepare for display" thing and then just save the layout with no reasons attached to fix it up. Easy to re-add these.

Thanks for gettting on it so quick.

**Comment by mmikkel** [comment] 2020-06-08 13:40
Yeah, it happens to the best of of us, right? :) The dumbest part is that I didn't catch it because I mostly tested on a migrated Craft 2 install, which had the correct column type in the database from the Craft 2 plugin.
