### ISSUE TITLE
Broken in Craft 3.7.46.

### ISSUE THREAD

**Issue by parthi-me** [mmikkel/Reasons-Craft3#17] opened 2022-07-01 08:44 UTC
Updated to Latest Craft CMS version 3.7.46 from 3.7.45.2 and it's broken the reasons plugin functionality. I can't see any obvious errors appearing, the fields with conditional rules are applied but they just don't appear in the entries.

**Comment by joshuarichard** [comment] 2022-07-01 17:56
Also experiencing this. Don't see logs on the server or the client that would give clues to the issue(s).

```
CraftCMS => 3.7.46
mmikkel/reasons => 2.3.0.1
```

**Comment by mmikkel** [comment] 2022-07-01 17:58
Hi, thanks for reporting this. I'll have a look at it ASAP.

**Comment by joshuarichard** [comment] 2022-07-01 18:02
Thanks a lot @mmikkel. Let me know if you need any version or implementation details from us.

**Comment by mmikkel** [comment] 2022-07-01 19:27
@parthi-me @joshuarichard I'm not able to reproduce this, so I need more info:

- Browser and version
- PHP version
- Database version
- Other plugins installed
- Multisite?
- Description of a specific conditional that isn't working (toggle field type, target field type, and the rule)

I'm also not seeing anything in the [v3 changelog] for 3.7.45.2 -> 3.7.46 that immediately jumps out as something that'd break Reasons.

If either of you could DM me (`@mmikkel`) on the Craft Discord with a database dump, composer.json and composer.lock file I can also try to dig further to reproduce with that.

**Comment by mmikkel** [comment] 2022-07-01 19:40
Also, check if Reasons' JS is even loading by looking in your browser dev tools' Networks panel. It should have an entry for a file called `render.js`:

![CleanShot 2022-07-01 at 21 39 16@2x](https://user-images.githubusercontent.com/298510/176959168-4cd174aa-6a4c-40c5-97b6-fb78b3a008a5.png)

**Comment by parthi-me** [comment] 2022-07-04 03:33
Hi @mmikkel , I see the dropdown field encryption is enabled in the latest Craft CMS update. This could be the reason for the above issue. I verified that before the update dropdown values are not encoded which you directly used to check against the values and displayed the respective fields. But as the values are encoded now we may need to decode and verify the values.

3.7.46 - Added craft\fields\BaseOptionsField::encodeValue().

**Comment by mmikkel** [comment] 2022-07-04 08:29
@parthi-me Thanks, you're absolutely correct. 

So it's specifically option toggle fields (i.e. dropdowns, radio buttons and checkboxes) that are broken, on 3.7.46. I'll look into a fix ASAP.

**Comment by mmikkel** [comment] 2022-07-04 08:48
Should be resolved in [Reasons 2.3.1](https://github.com/mmikkel/Reasons-Craft3/releases/tag/2.3.1). Thanks!

**Closed by mmikkel** 2022-07-04 08:48 UTC
Labels: bug, compatibility
